apiVersion: v1
kind: Secret
metadata:
  name: web3-postgres-cluster-secret
  namespace: postgres
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
